services:
  apache:
    build:
      dockerfile: docker/dockerfile-apache
    environment:
      TZ: Europe/Warsaw
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - ./:/var/www/products-api.local
      - ./docker/apache/vhost:/etc/apache2/sites-enabled
      - ./docker/apache/supervisor:/etc/supervisor
    ports:
      - '80:80'
    depends_on:
      - mysql
      - rabbitmq
      - mailcatcher

  mysql:
    platform: linux/amd64
    build:
      dockerfile: docker/dockerfile-mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: passwd
      MYSQL_DATABASE: products
      MYSQL_USER: products
      MYSQL_PASSWORD: products
      TZ: Europe/Warsaw
    volumes:
      - mysql_data:/var/lib/mysql:rw

  mailcatcher:
    platform: linux/amd64
    image: dockage/mailcatcher
    ports:
      - 1080:1080
    environment:
      TZ: Europe/Warsaw

  rabbitmq:
    platform: linux/amd64
    image: rabbitmq:4.1.0-management
    container_name: rabbitmq.local
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq:cached
      - rabbitmq_log:/var/log/rabbitmq:cached
    user: rabbitmq
    environment:
      TZ: Europe/Warsaw
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
      RABBITMQ_DEFAULT_VHOST: /

networks:
  products-api:
    driver: bridge

volumes:
  mysql_data:
  rabbitmq_data:
  rabbitmq_log:
