services:
  apache:
    build:
      dockerfile: docker/dockerfile-apache
    environment:
      TZ: Europe/Warsaw
    volumes:
      - ./:/var/www/products-api.local
      - ./docker/apache/vhost:/etc/apache2/sites-enabled
      - ./docker/apache/supervisor:/etc/supervisor
    ports:
      - '80:80'
    depends_on:
      rabbitmq:
        condition: service_healthy
      mysql:
        condition: service_healthy
      mailcatcher:
        condition: service_healthy

  mysql:
    platform: linux/amd64
    build:
      dockerfile: docker/dockerfile-mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: passwd
      MYSQL_DATABASE: products
      MYSQL_USER: products
      MYSQL_PASSWORD: products
      TZ: Europe/Warsaw
    volumes:
      - mysql_data:/var/lib/mysql:rw
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  mailcatcher:
    platform: linux/amd64
    image: dockage/mailcatcher
    ports:
      - 1080:1080
    environment:
      TZ: Europe/Warsaw
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://127.0.0.1:1080" ]
      interval: 5s
      timeout: 5s
      retries: 10

  rabbitmq:
    platform: linux/amd64
    image: rabbitmq:4.1.0-management
    container_name: rabbitmq.local
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq:cached
      - rabbitmq_log:/var/log/rabbitmq:cached
    user: rabbitmq
    environment:
      TZ: Europe/Warsaw
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
      RABBITMQ_DEFAULT_VHOST: /
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  products-api:
    driver: bridge

volumes:
  mysql_data:
  rabbitmq_data:
  rabbitmq_log:
